// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles configuration file management
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetItem retrieves a value from the configuration by key
 */
export function GetItem(key: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4122952478, key) as any;
    return $resultPromise;
}

/**
 * OnConfigChange registers a callback for configuration changes
 */
export function OnConfigChange(callback: any): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3283491376, callback) as any;
    return $resultPromise;
}

/**
 * RemoveItem removes a value from the configuration
 */
export function RemoveItem(key: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3426349016, key) as any;
    return $resultPromise;
}

/**
 * SetItem sets a value in the configuration
 */
export function SetItem(key: string, value: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1377100810, key, value) as any;
    return $resultPromise;
}
